name: Driver Build

on:
  workflow_dispatch:

  push:
    branches: [master]

jobs:
  build-x64:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - run: msbuild /t:build Sandboxie\SandboxDrv.sln /p:Configuration="SbieRelease" /p:Platform=x64 -maxcpucount:8
      - uses: actions/upload-artifact@v4.4.0
        with:
          name: x64
          path: Sandboxie/Bin/x64/SbieRelease/*